# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kconfig_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_kconf(object):
    def setupUi(self, MainWindow_kconf):
        MainWindow_kconf.setObjectName("MainWindow_kconf")
        MainWindow_kconf.resize(800, 600)
        icon = QtGui.QIcon.fromTheme("settings-configure")
        MainWindow_kconf.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow_kconf)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(6)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.left_panel = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.left_panel.setContentsMargins(0, 0, 0, 0)
        self.left_panel.setObjectName("left_panel")
        self.comboBox_config_files = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_config_files.setObjectName("comboBox_config_files")
        self.left_panel.addWidget(self.comboBox_config_files)
        self.listWidget_groups = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget_groups.setObjectName("listWidget_groups")
        self.left_panel.addWidget(self.listWidget_groups)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_reload = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_reload.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.pushButton_reload.setIcon(icon)
        self.pushButton_reload.setObjectName("pushButton_reload")
        self.horizontalLayout.addWidget(self.pushButton_reload)
        self.pushButton_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_save.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.pushButton_save.setIcon(icon)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.left_panel.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.right_panel = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.right_panel.setContentsMargins(0, 0, 0, 0)
        self.right_panel.setObjectName("right_panel")
        self.listWidget_keys = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.listWidget_keys.setObjectName("listWidget_keys")
        self.right_panel.addWidget(self.listWidget_keys)
        self.lineEdit_value = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_value.setEnabled(False)
        self.lineEdit_value.setObjectName("lineEdit_value")
        self.right_panel.addWidget(self.lineEdit_value)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow_kconf.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_kconf)
        self.statusbar.setObjectName("statusbar")
        MainWindow_kconf.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_kconf)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_kconf)

    def retranslateUi(self, MainWindow_kconf):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_kconf.setWindowTitle(_translate("MainWindow_kconf", "KConfig Browser"))
        self.pushButton_reload.setText(_translate("MainWindow_kconf", "Reload"))
        self.pushButton_save.setText(_translate("MainWindow_kconf", "Save"))
        self.lineEdit_value.setPlaceholderText(_translate("MainWindow_kconf", "Key value..."))
